"""
People Memory — Elora's knowledge of the people who matter to the user.

Stores rich profiles per person: name, relationship, appearance description,
contact info, notes, and a face description generated by Gemini Vision.

Firestore path: users/{uid}/people/{person_id}
Each doc:
  {
    id: str,
    name: str,
    relationship: str,           # "girlfriend", "mom", "colleague", "friend" …
    aliases: list[str],          # nicknames, "babe", "Maya", etc.
    appearance_description: str, # what they look like (from camera / user description)
    face_embedding_text: str,    # textual description used to match photos
    contact_email: str | None,
    contact_phone: str | None,
    notes: str,                  # freeform notes: interests, birthday, context
    created_at: datetime,
    updated_at: datetime,
  }
"""

from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger("elora.people")

_project = os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCP_PROJECT")
_db = None

try:
    if _project:
        from google.cloud import firestore
        _db = firestore.Client(project=_project)
        logger.info(f"People memory Firestore ready (project={_project})")
except Exception as e:
    logger.warning(f"People memory Firestore unavailable: {e}")

# In-memory fallback (dev / no Firestore)
_mem_store: dict[str, dict] = {}  # uid -> {person_id -> doc}


def _people_col(user_id: str):
    if _db:
        return _db.collection("users").document(user_id).collection("people")
    return None


# ---------------------------------------------------------------------------
# Tool: remember a person
# ---------------------------------------------------------------------------

def remember_person(
    name: str,
    relationship: str,
    appearance_description: str = "",
    contact_email: str = "",
    contact_phone: str = "",
    notes: str = "",
    aliases: str = "",
    user_id: str = "",
) -> dict:
    """Store or update a person in Elora's people memory.

    Call this whenever the user introduces someone important, tells you about
    their girlfriend, mentions their mom by name, shares a colleague's contact,
    or describes what someone looks like via camera.

    Args:
        name:                   Full name or first name. e.g. "Maya", "Jake Chen"
        relationship:           How they relate to the user. e.g. "girlfriend", "mom",
                                "best friend", "work colleague", "brother"
        appearance_description: What this person looks like — described by the user
                                or inferred from a photo shown via camera.
                                Include: hair colour, height, distinguishing features.
                                e.g. "tall, curly dark hair, usually wears glasses"
        contact_email:          Their email address if known.
        contact_phone:          Their phone number if known.
        notes:                  Any other context: birthday, shared history, interests,
                                things to remember. e.g. "birthday March 3rd, loves sushi"
        aliases:                Comma-separated alternative names. e.g. "babe,my gf,M"
        user_id:                Injected automatically — do not pass.

    Returns:
        dict: {"status": "ok", "person_id": str, "name": str}
    """
    from elora_agent.shared import get_user_id
    uid = user_id or get_user_id()

    # Check if person already exists by name match (case-insensitive)
    existing = _find_by_name(uid, name)

    person_id = existing.get("id") if existing else str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    # Build aliases list
    alias_list = [a.strip() for a in aliases.split(",") if a.strip()] if aliases else []
    if name.lower() not in [a.lower() for a in alias_list]:
        alias_list.insert(0, name)

    doc = {
        "id": person_id,
        "name": name,
        "relationship": relationship,
        "aliases": alias_list,
        "appearance_description": appearance_description or (existing.get("appearance_description", "") if existing else ""),
        "face_embedding_text": _build_face_text(name, relationship, appearance_description),
        "contact_email": contact_email or (existing.get("contact_email", "") if existing else ""),
        "contact_phone": contact_phone or (existing.get("contact_phone", "") if existing else ""),
        "notes": notes or (existing.get("notes", "") if existing else ""),
        "created_at": existing.get("created_at", now) if existing else now,
        "updated_at": now,
    }

    col = _people_col(uid)
    if col:
        try:
            col.document(person_id).set(doc)
        except Exception as e:
            logger.warning(f"[People] Firestore write failed, using in-memory fallback: {e}")
            if uid not in _mem_store:
                _mem_store[uid] = {}
            _mem_store[uid][person_id] = doc
    else:
        if uid not in _mem_store:
            _mem_store[uid] = {}
        _mem_store[uid][person_id] = doc

    action = "Updated" if existing else "Remembered"
    logger.info(f"[People] {action} '{name}' ({relationship}) for user={uid}")
    return {"status": "ok", "person_id": person_id, "name": name, "action": action.lower()}


def _build_face_text(name: str, relationship: str, appearance: str) -> str:
    """Build a searchable text description for face/photo matching."""
    parts = [f"{name} ({relationship})"]
    if appearance:
        parts.append(appearance)
    return " — ".join(parts)


def _find_by_name(uid: str, name: str) -> dict | None:
    """Find a person by name or alias (case-insensitive)."""
    people = _get_all_people(uid)
    name_lower = name.lower()
    for p in people:
        if p.get("name", "").lower() == name_lower:
            return p
        for alias in p.get("aliases", []):
            if alias.lower() == name_lower:
                return p
    return None


def _get_all_people(uid: str) -> list[dict]:
    col = _people_col(uid)
    if col:
        try:
            return [doc.to_dict() for doc in col.stream() if doc.to_dict()]
        except Exception as e:
            logger.error(f"[People] Firestore read error: {e}")
            return []
    return list((_mem_store.get(uid) or {}).values())


# ---------------------------------------------------------------------------
# Tool: recall a person
# ---------------------------------------------------------------------------

def recall_person(name_or_relationship: str, user_id: str = "") -> dict:
    """Look up everything Elora knows about a specific person.

    Use this before sending an email/message to someone, when the user refers
    to someone by name or relationship, or when you need their contact info.

    Args:
        name_or_relationship: Name, alias, or relationship.
                              e.g. "Maya", "my girlfriend", "mom", "Jake"
        user_id:              Injected automatically.

    Returns:
        dict: Person profile if found, or {"status": "not_found"}
    """
    from elora_agent.shared import get_user_id
    uid = user_id or get_user_id()

    people = _get_all_people(uid)
    query = name_or_relationship.lower().strip()

    # Try exact name/alias match
    for p in people:
        if p.get("name", "").lower() == query:
            return {"status": "found", "person": _format_person(p)}
        for alias in p.get("aliases", []):
            if alias.lower() == query:
                return {"status": "found", "person": _format_person(p)}

    # Try relationship match
    for p in people:
        if p.get("relationship", "").lower() == query:
            return {"status": "found", "person": _format_person(p)}

    # Try partial name match
    for p in people:
        if query in p.get("name", "").lower():
            return {"status": "found", "person": _format_person(p)}

    return {"status": "not_found", "query": name_or_relationship,
            "suggestion": "Try introducing them: 'Elora, this is my girlfriend Maya'"}


def _format_person(p: dict) -> dict:
    """Clean up person doc for agent consumption."""
    return {
        "name": p.get("name", ""),
        "relationship": p.get("relationship", ""),
        "appearance": p.get("appearance_description", ""),
        "email": p.get("contact_email", ""),
        "phone": p.get("contact_phone", ""),
        "notes": p.get("notes", ""),
        "aliases": p.get("aliases", []),
    }


# ---------------------------------------------------------------------------
# Tool: list all people
# ---------------------------------------------------------------------------

def list_people(user_id: str = "") -> dict:
    """Return a summary of everyone Elora knows about.

    Use this when the user asks "who do you know?" or "what do you know about
    my contacts?" or when you need to find someone's contact to send them a message.

    Args:
        user_id: Injected automatically.

    Returns:
        dict: {"people": [...], "count": int}
    """
    from elora_agent.shared import get_user_id
    uid = user_id or get_user_id()

    people = _get_all_people(uid)
    summaries = [
        {
            "name": p.get("name", ""),
            "relationship": p.get("relationship", ""),
            "email": p.get("contact_email", ""),
            "phone": p.get("contact_phone", ""),
            "notes_preview": (p.get("notes", "") or "")[:80],
        }
        for p in people
    ]
    return {"people": summaries, "count": len(summaries)}


# ---------------------------------------------------------------------------
# Tool: update appearance from a photo (called after camera capture)
# ---------------------------------------------------------------------------

def update_person_appearance(name: str, appearance_description: str, user_id: str = "") -> dict:
    """Update the visual appearance description for a known person.

    Call this when the user shows Elora a photo and says "this is [name]"
    or "remember what she looks like". Use Gemini's vision description
    as the appearance_description.

    Args:
        name:                   Name of the person to update.
        appearance_description: Visual description from the photo.
        user_id:                Injected automatically.

    Returns:
        dict: {"status": "ok"} or {"status": "not_found"}
    """
    from elora_agent.shared import get_user_id
    uid = user_id or get_user_id()

    existing = _find_by_name(uid, name)
    if not existing:
        return {"status": "not_found", "name": name,
                "suggestion": f"I don't know {name} yet. Try: remember_person(name='{name}', ...)"}

    col = _people_col(uid)
    updates = {
        "appearance_description": appearance_description,
        "face_embedding_text": _build_face_text(name, existing.get("relationship", ""), appearance_description),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    if col:
        try:
            col.document(existing["id"]).update(updates)
        except Exception as e:
            logger.warning(f"[People] Firestore update failed, using in-memory fallback: {e}")
            uid_store = _mem_store.get(uid, {})
            if existing["id"] in uid_store:
                uid_store[existing["id"]].update(updates)
    else:
        uid_store = _mem_store.get(uid, {})
        if existing["id"] in uid_store:
            uid_store[existing["id"]].update(updates)

    logger.info(f"[People] Updated appearance for '{name}' for user={uid}")
    return {"status": "ok", "name": name}


# ---------------------------------------------------------------------------
# Photo matching helper (used by photo search)
# ---------------------------------------------------------------------------

def find_people_in_description(photo_description: str, user_id: str) -> list[dict]:
    """Given a Gemini vision description of a photo, find known people who match.

    Returns a list of matching person profiles, best-match first.
    """
    people = _get_all_people(user_id)
    matches = []

    desc_lower = photo_description.lower()
    for p in people:
        score = 0
        name_lower = p.get("name", "").lower()
        rel_lower = p.get("relationship", "").lower()
        appearance = p.get("appearance_description", "").lower()

        # Name appears in photo description (e.g. tagged, mentioned)
        if name_lower and name_lower in desc_lower:
            score += 10

        # Appearance features match
        if appearance:
            for feature in appearance.split(","):
                f = feature.strip()
                if f and f in desc_lower:
                    score += 2

        # Relationship keywords
        if rel_lower in desc_lower:
            score += 3

        if score > 0:
            matches.append({"score": score, "person": _format_person(p)})

    matches.sort(key=lambda x: x["score"], reverse=True)
    return [m["person"] for m in matches]
